package com.example.releasethekraken.model;

import com.example.releasethekraken.controller.NotificationService;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

/// Responsibilities                                                    Collaborators
/// ---------------------------------------------------------------------------------------
/// Randomly select entrants from WaitingList up to capacity            WaitingList
/// Handle invitation workflow (invite → accept/decline → refill spot)	Event
/// Support redraw when someone declines or later cancels	            NotificationService
/// Produce final accepted attendee list


//javadocs for this class generated by ChatGPT, 2026-03-13
/**
 * Manages the lottery drawing process for events.
 *
 * This class randomly selects entrants from a waiting list up to the event's capacity.
 * It handles initial draws as well as replacement draws if spots become available.
 * Winners are notified via {@link NotificationService}.
 */
public class LotteryManager {

    //Takes in all entrants from an event and capacity, and chooses random people up to its capacity, returns accepted entrants
    // Notification wiring is intentionally lazy. The current draw methods only compute winners
    // and do not need live Firebase dependencies during JVM unit tests.
    NotificationRepository notifRepo;
    NotificationService notifService;

    /**
     * Performs the initial lottery draw for an event.
     *
     * Randomly selects up to {@code capacity} entrants from the provided list.
     *
     * @param event       The event for which to draw winners
     * @param allEntrantsList List of all current entrants
     * @param capacity    Maximum number of winners to select
     * @return LotteryResult class containing accepted entrants and rejected entrants
     */
    public LotteryResult drawEntrants(Event event, List<String> allEntrantsList, int capacity) {
        Random rand = new Random();
        ArrayList<String> allEntrants = new ArrayList<>(allEntrantsList);
        ArrayList<String> acceptedEntrants = new ArrayList<String>();

        //Loops through all entrants until reaches capacity, or no more entrants
        for (int i = 0; (i < capacity) && (!allEntrants.isEmpty()); i++) {
            String acceptedEntrant = allEntrants.remove(rand.nextInt(allEntrants.size()));
            acceptedEntrants.add(acceptedEntrant);

        }

        ArrayList<String> rejectedEntrants = new ArrayList<String>();
        //Loops through all remaining undrawn entrants and adds them to a rejectedEntrant arrayList
        while (!allEntrants.isEmpty()) {
            String rejectedEntrant = allEntrants.remove(0);
            rejectedEntrants.add(rejectedEntrant);
        }


        return new LotteryResult(acceptedEntrants, rejectedEntrants);
    }

    //Takes in remaining entrants from event, accepted entrants and capacity, and fills up the accepted entrants with randomly from remaining entrants
    /**
     * Fills remaining spots in an event with replacement entrants.
     *
     * Randomly selects entrants from the remaining list until the event's capacity
     * is reached, adds them to the accepted list, and sends notifications.
     *
     * @param event            The event for which to draw replacement winners
     * @param allEntrants      List of remaining entrants
     * @param acceptedEntrants List of already accepted entrants
     * @param capacity         Maximum number of winners for the event
     * @return Updated list of accepted entrants
     */
    public ArrayList<String> drawReplacementEntrants(Event event, ArrayList<String> allEntrants, ArrayList<String> acceptedEntrants, int capacity) {
        Random rand = new Random();

        for (int i = acceptedEntrants.size(); (i < capacity) && (!allEntrants.isEmpty()); i++) {
            String acceptedEntrant = allEntrants.remove(rand.nextInt(allEntrants.size()));
            acceptedEntrants.add(acceptedEntrant);

        }
        return acceptedEntrants;
    }
}
