package com.example.releasethekraken.controller;

import android.content.Context;

import androidx.annotation.NonNull;
import androidx.work.Worker;
import androidx.work.WorkerParameters;

import com.example.releasethekraken.model.Event;
import com.example.releasethekraken.model.EventRepository;
import com.example.releasethekraken.model.LotteryManager;
import com.example.releasethekraken.model.WaitingListRepository;
import com.example.releasethekraken.controller.WaitingListService;
import com.example.releasethekraken.controller.NotificationService;
import com.example.releasethekraken.model.NotificationRepository;

import java.util.ArrayList;

//following class generated by ChatGPT when given this class and context of related code. 2026-03-13
public class DrawEntrantsWorker extends Worker {

    public DrawEntrantsWorker(@NonNull Context context, @NonNull WorkerParameters params) {
        super(context, params);
    }

    @NonNull
    @Override
    public Result doWork() {

        String eventId = getInputData().getString("eventId");

        if (eventId == null) {
            return Result.failure();
        }

        EventRepository eventRepo = new EventRepository();
        WaitingListRepository waitingListRepo = new WaitingListRepository();
        NotificationService notifService = new NotificationService(new NotificationRepository());
        WaitingListService waitingListService = new WaitingListService(waitingListRepo);

        // Step 1: Get event details from Firestore
        eventRepo.getEventById(eventId, new EventRepository.EventCallback() {
            @Override
            public void onSuccess(Event event) {

                // Step 2: Get all entrants for this event
                waitingListRepo.getAllEntrants(event.getEventId(), new WaitingListRepository.EntrantsCallback() {
                    @Override
                    public void onResult(ArrayList<String> entrants) {

                        if (entrants.isEmpty()) {
                            // No entrants, nothing to draw
                            return;
                        }

                        // Step 3: Draw winners
                        int capacity = event.getCapacity(); // Make sure Event has capacity field
                        ArrayList<String> winners = new LotteryManager().drawEntrants(event, entrants, capacity);

                        // Step 4: Save winners to Firestore
                        waitingListRepo.saveAcceptedEntrants(event.getEventId(), winners, new WaitingListRepository.CompletionCallback() {
                            @Override
                            public void onSuccess() {
                                // Step 5: Send notifications to winners
                                for (String winnerId : winners) {
                                    notifService.sendWinNotification(event, winnerId, new NotificationService.NotificationCallback() {
                                        @Override
                                        public void onResult(NotificationService.NotificationResult result) {
                                            // Log success or update analytics
                                        }

                                        @Override
                                        public void onError(Exception e) {
                                            e.printStackTrace(); // Log failure, but don't block
                                        }
                                    });
                                }
                            }

                            @Override
                            public void onError(Exception e) {
                                e.printStackTrace();
                            }
                        });

                    }

                    @Override
                    public void onError(Exception e) {
                        e.printStackTrace();
                    }
                });

            }

            @Override
            public void onError(Exception e) {
                e.printStackTrace();
            }
        });

        // Worker itself returns success; async callbacks handle Firestore operations
        return Result.success();
    }
}